"use client";
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { useAuthStore } from "@/lib/store";
import { useJobsStore } from "@/lib/jobs-store";
import { generateMilestones } from "@/lib/gemini";
import { Zap, Plus, X, ChevronRight, Cpu, AlertTriangle, CheckCircle, Clock, DollarSign, Loader2, Sparkles, Shield, Edit3, ArrowLeft } from "lucide-react";

const SKILL_SUGGESTIONS = [
    "React", "Node.js", "Python", "TypeScript", "Next.js", "PostgreSQL",
    "Solidity", "Rust", "Go", "Django", "Flutter", "Swift",
    "Figma", "UI/UX Design", "Brand Identity", "Motion Design",
    "Content Writing", "Technical Writing", "SEO", "Video Editing",
    "Data Analysis", "Machine Learning", "DevOps", "AWS", "Docker"
];

export default function PostJobPage() {
    const navigate = useNavigate();
    const user = useAuthStore((s) => s.user);
    const addJob = useJobsStore((s) => s.addJob);

    // Step 1: Job basics
    const [title, setTitle] = useState("");
    const [description, setDescription] = useState("");
    const [budget, setBudget] = useState("");
    const [skills, setSkills] = useState([]);
    const [skillInput, setSkillInput] = useState("");
    const [deadline, setDeadline] = useState("");

    // Step 2: AI generation
    const [step, setStep] = useState(1);
    const [generating, setGenerating] = useState(false);
    const [plan, setPlan] = useState(null);
    const [genError, setGenError] = useState("");
    const [editingMilestone, setEditingMilestone] = useState(null);

    // Step 3: Review & post
    const [posting, setPosting] = useState(false);

    function addSkill(skill) {
        const s = skill.trim();
        if (s && !skills.includes(s) && skills.length < 10) {
            setSkills([...skills, s]);
            setSkillInput("");
        }
    }

    function removeSkill(skill) {
        setSkills(skills.filter((s) => s !== skill));
    }

    async function handleGeneratePlan() {
        if (!title || !description || !budget || skills.length === 0) {
            setGenError("Please fill in all fields and add at least one skill.");
            return;
        }

        setGenError("");
        setGenerating(true);

        try {
            const result = await generateMilestones(title, description, Number(budget), skills);
            setPlan(result);
            setStep(2);
        }
        catch (e) {
            setGenError("AI generation failed: " + (e.message || "Unknown error. Check your Gemini API key."));
        }
        finally {
            setGenerating(false);
        }
    }

    function updateMilestone(id, patch) {
        if (!plan)
            return;
        setPlan({
            ...plan,
            milestones: plan.milestones.map((m) => (m.id === id ? { ...m, ...patch } : m)),
        });
    }

    async function handlePost() {
        if (!plan || !user) return;
        setPosting(true);
        try {
            const token = localStorage.getItem('paylance_token');
            const res = await fetch(`${import.meta.env.VITE_API_URL || "http://localhost:5000/api"}/jobs`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${token}` },
                body: JSON.stringify({
                    employer_id: user.id,
                    employer_name: user.name,
                    title,
                    description,
                    budget: Number(budget),
                    currency: 'USD',
                    deadline: deadline || new Date(Date.now() + 30 * 86400000).toISOString(),
                    skills: skills.join(','),
                    milestones: plan.milestones.map(m => ({
                        id: m.id,
                        title: m.title,
                        description: m.description,
                        amount: m.amount,
                        deliverables: m.deliverables,
                        acceptanceCriteria: m.acceptanceCriteria
                    })),
                })
            });

            const data = await res.json();
            if (!res.ok) throw new Error(data.error || 'Failed to post job');

            const jobId = data.jobId;
            // Use the milestone IDs generated by the server — never the local mock IDs
            const serverMilestones = data.milestones || plan.milestones;

            // Also sync to Zustand store for immediate local access
            addJob({
                id: jobId,
                employerId: user.id,
                employerName: user.name,
                title,
                description,
                skills,
                budget: Number(budget),
                status: 'OPEN',
                milestones: serverMilestones.map((m) => ({ ...m, status: 'LOCKED' })),
                aiPlan: plan,
                createdAt: new Date().toISOString(),
                deadline: deadline || new Date(Date.now() + 30 * 86400000).toISOString(),
                escrow: { status: 'PENDING', total: Number(budget), funded: 0, released: 0 },
                downloadUnlocked: false,
            });

            navigate(`/dashboard/employer/jobs/${jobId}/matches`);
        } catch (err) {
            alert('Error posting job: ' + err.message);
        } finally {
            setPosting(false);
        }
    }


    const budgetNum = Number(budget) || 0;

    return (<div style={{ padding: "1.5rem", maxWidth: 800, margin: "0 auto" }}>
      {/* Header */}
      <div style={{ marginBottom: "2rem" }}>
        <button onClick={() => step === 1 ? navigate(-1) : setStep((s) => (s - 1))} style={{ display: "flex", alignItems: "center", gap: "0.4rem", background: "none", border: "none", color: "hsl(220 15% 55%)", cursor: "pointer", fontSize: "0.875rem", marginBottom: "1rem", padding: 0 }}>
          <ArrowLeft size={16}/> {step === 1 ? "Back to Jobs" : "Back"}
        </button>
        <h1 className="font-heading" style={{ fontSize: "1.75rem", fontWeight: 800, color: "white", letterSpacing: "-0.03em" }}>
          {step === 1 ? "Post a New Job" : step === 2 ? "AI Milestone Plan" : "Review & Post"}
        </h1>
        <p style={{ color: "hsl(220 15% 55%)", marginTop: "0.35rem", fontSize: "0.9rem" }}>
          {step === 1
            ? "Describe your project and let Gemini AI structure it into verified milestones."
            : step === 2
                ? "Gemini has structured your project. Review and adjust milestones before posting."
                : "Your job is ready to go live. Freelancers will be AI-matched to your requirements."}
        </p>
      </div>

      {/* Step indicators */}
      <div style={{ display: "flex", gap: "0.5rem", marginBottom: "2rem", alignItems: "center" }}>
        {[1, 2, 3].map((s, i) => (<div key={s} style={{ display: "flex", alignItems: "center", gap: "0.5rem" }}>
            <div style={{
                width: 28, height: 28, borderRadius: "50%", display: "flex", alignItems: "center", justifyContent: "center",
                fontSize: "0.75rem", fontWeight: 700, transition: "all 0.3s",
                background: step >= s ? "hsl(217 91% 55%)" : "hsl(220 20% 16%)",
                color: step >= s ? "white" : "hsl(220 15% 45%)",
                boxShadow: step === s ? "0 0 16px hsl(217 91% 55% / 0.4)" : "none",
            }}>
              {step > s ? <CheckCircle size={14}/> : s}
            </div>
            <span style={{ fontSize: "0.8rem", color: step >= s ? "white" : "hsl(220 15% 45%)", fontWeight: step === s ? 600 : 400 }}>
              {["Job Details", "AI Milestones", "Post"][i]}
            </span>
            {s < 3 && <ChevronRight size={14} color="hsl(220 15% 35%)"/>}
          </div>))}
      </div>

      {/* ─── STEP 1: Job Details ─────────────────────────────────────────── */}
      {step === 1 && (<div style={{ display: "flex", flexDirection: "column", gap: "1.25rem" }}>
          <div className="card" style={{ display: "flex", flexDirection: "column", gap: "1.25rem" }}>
            {/* Title */}
            <div>
              <label style={{ display: "block", fontSize: "0.8rem", fontWeight: 600, color: "hsl(220 15% 65%)", marginBottom: "0.5rem", textTransform: "uppercase", letterSpacing: "0.05em" }}>
                Job Title
              </label>
              <input id="job-title" className="input" placeholder="e.g. Build a React dashboard with real-time analytics" value={title} onChange={(e) => setTitle(e.target.value)} style={{ fontSize: "1rem" }}/>
            </div>

            {/* Description */}
            <div>
              <label style={{ display: "block", fontSize: "0.8rem", fontWeight: 600, color: "hsl(220 15% 65%)", marginBottom: "0.5rem", textTransform: "uppercase", letterSpacing: "0.05em" }}>
                Project Description
              </label>
              <textarea id="job-description" className="input" placeholder="Describe what you need built. Be specific — Gemini AI will use this to generate verifiable milestones with acceptance criteria. Include tech requirements, integrations, and success metrics." value={description} onChange={(e) => setDescription(e.target.value)} rows={6} style={{ resize: "vertical", lineHeight: 1.6 }}/>
              <div style={{ fontSize: "0.75rem", color: "hsl(220 15% 45%)", marginTop: "0.35rem" }}>
                {description.length} characters · More detail = better AI milestone breakdown
              </div>
            </div>

            {/* Budget + Deadline */}
            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "1rem" }}>
              <div>
                <label style={{ display: "block", fontSize: "0.8rem", fontWeight: 600, color: "hsl(220 15% 65%)", marginBottom: "0.5rem", textTransform: "uppercase", letterSpacing: "0.05em" }}>
                  Total Budget (USD)
                </label>
                <div style={{ position: "relative" }}>
                  <span style={{ position: "absolute", left: "0.75rem", top: "50%", transform: "translateY(-50%)", color: "hsl(220 15% 50%)", fontSize: "0.9rem" }}>$</span>
                  <input id="job-budget" className="input" type="number" placeholder="2500" value={budget} onChange={(e) => setBudget(e.target.value)} style={{ paddingLeft: "1.75rem" }}/>
                </div>
              </div>
              <div>
                <label style={{ display: "block", fontSize: "0.8rem", fontWeight: 600, color: "hsl(220 15% 65%)", marginBottom: "0.5rem", textTransform: "uppercase", letterSpacing: "0.05em" }}>
                  Deadline (optional)
                </label>
                <input className="input" type="date" value={deadline} onChange={(e) => setDeadline(e.target.value)} min={new Date().toISOString().split("T")[0]}/>
              </div>
            </div>

            {/* Skills */}
            <div>
              <label style={{ display: "block", fontSize: "0.8rem", fontWeight: 600, color: "hsl(220 15% 65%)", marginBottom: "0.5rem", textTransform: "uppercase", letterSpacing: "0.05em" }}>
                Required Skills ({skills.length}/10)
              </label>
              <div style={{ display: "flex", gap: "0.5rem", marginBottom: "0.75rem", flexWrap: "wrap" }}>
                {skills.map((s) => (<span key={s} style={{ display: "flex", alignItems: "center", gap: "0.3rem", padding: "0.3rem 0.6rem", background: "hsl(217 91% 55% / 0.15)", border: "1px solid hsl(217 91% 55% / 0.3)", borderRadius: 6, fontSize: "0.82rem", color: "hsl(217 91% 75%)" }}>
                    {s}
                    <button onClick={() => removeSkill(s)} style={{ background: "none", border: "none", cursor: "pointer", color: "hsl(217 91% 55%)", display: "flex", padding: 0 }}>
                      <X size={12}/>
                    </button>
                  </span>))}
              </div>
              <div style={{ display: "flex", gap: "0.5rem" }}>
                <input id="job-skills" className="input" placeholder="Add a skill..." value={skillInput} onChange={(e) => setSkillInput(e.target.value)} onKeyDown={(e) => e.key === "Enter" && addSkill(skillInput)} style={{ flex: 1 }}/>
                <button id="add-skill-btn" onClick={() => addSkill(skillInput)} className="btn btn-outline" style={{ flexShrink: 0 }}>
                  <Plus size={16}/>
                </button>
              </div>
              {/* Quick add suggestions */}
              <div style={{ display: "flex", gap: "0.4rem", flexWrap: "wrap", marginTop: "0.6rem" }}>
                {SKILL_SUGGESTIONS.filter((s) => !skills.includes(s)).slice(0, 8).map((s) => (<button key={s} onClick={() => addSkill(s)} style={{ padding: "0.2rem 0.6rem", background: "hsl(220 16% 12%)", border: "1px solid hsl(220 20% 20%)", borderRadius: 6, fontSize: "0.75rem", color: "hsl(220 15% 55%)", cursor: "pointer", transition: "all 0.15s" }} onMouseEnter={(e) => { e.currentTarget.style.borderColor = "hsl(217 91% 55% / 0.4)"; e.currentTarget.style.color = "white"; }} onMouseLeave={(e) => { e.currentTarget.style.borderColor = "hsl(220 20% 20%)"; e.currentTarget.style.color = "hsl(220 15% 55%)"; }}>
                    + {s}
                  </button>))}
              </div>
            </div>
          </div>

          {/* AI Banner */}
          <div style={{ background: "linear-gradient(135deg, hsl(217 91% 55% / 0.1), hsl(200 100% 60% / 0.05))", border: "1px solid hsl(217 91% 55% / 0.2)", borderRadius: 12, padding: "1rem 1.25rem", display: "flex", alignItems: "center", gap: "1rem" }}>
            <div style={{ width: 40, height: 40, borderRadius: 10, background: "linear-gradient(135deg, hsl(217 91% 55%), hsl(200 100% 60%))", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}>
              <Sparkles size={20} color="white"/>
            </div>
            <div>
              <div style={{ fontSize: "0.9rem", fontWeight: 700, color: "white", marginBottom: "0.2rem" }}>Gemini AI Milestone Generator</div>
              <div style={{ fontSize: "0.8rem", color: "hsl(220 15% 60%)" }}>Your description will be structured into verifiable milestones with acceptance criteria — the foundation of Paylance's escrow system.</div>
            </div>
          </div>

          {genError && (<div style={{ background: "hsl(0 84% 60% / 0.1)", border: "1px solid hsl(0 84% 60% / 0.3)", borderRadius: 8, padding: "0.75rem 1rem", fontSize: "0.85rem", color: "hsl(0 84% 75%)", display: "flex", alignItems: "center", gap: "0.5rem" }}>
              <AlertTriangle size={16}/> {genError}
            </div>)}

          <button id="create-job-btn" onClick={handleGeneratePlan} disabled={generating} className="btn btn-primary" style={{ padding: "0.875rem 1.5rem", fontSize: "1rem", fontWeight: 700, gap: "0.5rem" }}>
            {generating ? (<><Loader2 size={18} style={{ animation: "spin 1s linear infinite" }}/> Gemini is structuring your project...</>) : (<><Cpu size={18}/> Generate AI Milestone Plan</>)}
          </button>
        </div>)}

      {/* ─── STEP 2: AI Milestones ───────────────────────────────────────── */}
      {step === 2 && plan && (<div style={{ display: "flex", flexDirection: "column", gap: "1.25rem" }}>
          {/* AI Summary card */}
          <div style={{ background: "linear-gradient(135deg, hsl(145 65% 42% / 0.08), hsl(145 65% 42% / 0.03))", border: "1px solid hsl(145 65% 42% / 0.25)", borderRadius: 12, padding: "1.25rem" }}>
            <div style={{ display: "flex", alignItems: "center", gap: "0.75rem", marginBottom: "0.75rem" }}>
              <div style={{ width: 32, height: 32, borderRadius: 8, background: "hsl(145 65% 42% / 0.2)", display: "flex", alignItems: "center", justifyContent: "center" }}>
                <Sparkles size={16} color="hsl(145 65% 55%)"/>
              </div>
              <span style={{ fontSize: "0.9rem", fontWeight: 700, color: "hsl(145 65% 55%)" }}>Gemini AI Analysis</span>
            </div>
            <p style={{ fontSize: "0.875rem", color: "hsl(220 15% 70%)", lineHeight: 1.6 }}>{plan.aiSummary}</p>
            <div style={{ display: "flex", gap: "1.5rem", marginTop: "1rem", flexWrap: "wrap" }}>
              <div style={{ display: "flex", alignItems: "center", gap: "0.4rem" }}>
                <DollarSign size={14} color="hsl(145 65% 50%)"/>
                <span style={{ fontSize: "0.8rem", color: "white", fontWeight: 600 }}>${plan.totalBudget.toLocaleString()} total</span>
              </div>
              <div style={{ display: "flex", alignItems: "center", gap: "0.4rem" }}>
                <Clock size={14} color="hsl(200 100% 60%)"/>
                <span style={{ fontSize: "0.8rem", color: "white", fontWeight: 600 }}>{plan.estimatedDays} days estimated</span>
              </div>
              <div style={{ display: "flex", alignItems: "center", gap: "0.4rem" }}>
                <Zap size={14} color="hsl(38 92% 55%)"/>
                <span style={{ fontSize: "0.8rem", color: "white", fontWeight: 600 }}>{plan.milestones.length} milestones</span>
              </div>
            </div>
          </div>

          {/* Risk flags */}
          {plan.riskFlags?.length > 0 && (<div style={{ background: "hsl(38 92% 50% / 0.08)", border: "1px solid hsl(38 92% 50% / 0.25)", borderRadius: 10, padding: "1rem" }}>
              <div style={{ display: "flex", alignItems: "center", gap: "0.5rem", marginBottom: "0.5rem" }}>
                <AlertTriangle size={15} color="hsl(38 92% 60%)"/>
                <span style={{ fontSize: "0.82rem", fontWeight: 700, color: "hsl(38 92% 65%)" }}>AI Risk Flags</span>
              </div>
              {plan.riskFlags.map((flag, i) => (<div key={i} style={{ fontSize: "0.8rem", color: "hsl(220 15% 65%)", padding: "0.25rem 0", borderBottom: i < plan.riskFlags.length - 1 ? "1px solid hsl(220 20% 16%)" : "none" }}>
                  · {flag}
                </div>))}
            </div>)}

          {/* Milestones */}
          <div style={{ display: "flex", flexDirection: "column", gap: "1rem" }}>
            {plan.milestones.map((milestone, i) => (<div key={milestone.id} className="card" style={{ position: "relative", overflow: "hidden" }}>
                {/* Number indicator */}
                <div style={{ position: "absolute", top: 0, left: 0, width: 4, height: "100%", background: `linear-gradient(180deg, hsl(${217 - i * 15} 91% 55%), hsl(${200 - i * 10} 100% 60%))` }}/>
                <div style={{ paddingLeft: "0.75rem" }}>
                  <div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", marginBottom: "0.75rem", gap: "1rem" }}>
                    <div style={{ flex: 1 }}>
                      <div style={{ display: "flex", alignItems: "center", gap: "0.5rem", marginBottom: "0.25rem" }}>
                        <span style={{ fontSize: "0.72rem", fontWeight: 700, color: "hsl(217 91% 65%)", textTransform: "uppercase", letterSpacing: "0.08em" }}>Milestone {i + 1}</span>
                      </div>
                      {editingMilestone === milestone.id ? (<input className="input" value={milestone.title} onChange={(e) => updateMilestone(milestone.id, { title: e.target.value })} style={{ fontWeight: 700, fontSize: "1rem" }} autoFocus onBlur={() => setEditingMilestone(null)}/>) : (<div style={{ display: "flex", alignItems: "center", gap: "0.5rem" }}>
                          <h3 className="font-heading" style={{ fontSize: "1rem", fontWeight: 700, color: "white" }}>{milestone.title}</h3>
                          <button onClick={() => setEditingMilestone(milestone.id)} style={{ background: "none", border: "none", cursor: "pointer", color: "hsl(220 15% 45%)", display: "flex" }}>
                            <Edit3 size={13}/>
                          </button>
                        </div>)}
                    </div>
                    <div style={{ textAlign: "right", flexShrink: 0 }}>
                      <div className="font-heading" style={{ fontSize: "1.15rem", fontWeight: 800, color: "white" }}>
                        ${milestone.amount.toLocaleString()}
                      </div>
                      <div style={{ fontSize: "0.72rem", color: "hsl(220 15% 50%)" }}>{milestone.durationDays}d</div>
                    </div>
                  </div>

                  <p style={{ fontSize: "0.82rem", color: "hsl(220 15% 65%)", marginBottom: "0.75rem", lineHeight: 1.5 }}>{milestone.description}</p>

                  {/* Deliverables */}
                  <div style={{ marginBottom: "0.75rem" }}>
                    <div style={{ fontSize: "0.72rem", fontWeight: 700, color: "hsl(220 15% 45%)", textTransform: "uppercase", letterSpacing: "0.06em", marginBottom: "0.4rem" }}>Deliverables</div>
                    <div style={{ display: "flex", flexWrap: "wrap", gap: "0.35rem" }}>
                      {milestone.deliverables.map((d, di) => (<span key={di} style={{ fontSize: "0.75rem", color: "hsl(200 100% 70%)", background: "hsl(200 100% 60% / 0.1)", border: "1px solid hsl(200 100% 60% / 0.2)", padding: "0.15rem 0.5rem", borderRadius: 4 }}>
                          {d}
                        </span>))}
                    </div>
                  </div>

                  {/* Acceptance criteria */}
                  <div style={{ background: "hsl(145 65% 42% / 0.06)", border: "1px solid hsl(145 65% 42% / 0.15)", borderRadius: 6, padding: "0.6rem 0.75rem" }}>
                    <div style={{ display: "flex", alignItems: "center", gap: "0.4rem", marginBottom: "0.25rem" }}>
                      <Shield size={12} color="hsl(145 65% 50%)"/>
                      <span style={{ fontSize: "0.72rem", fontWeight: 700, color: "hsl(145 65% 55%)", textTransform: "uppercase", letterSpacing: "0.06em" }}>AI Acceptance Criteria</span>
                    </div>
                    <p style={{ fontSize: "0.78rem", color: "hsl(220 15% 65%)", lineHeight: 1.5 }}>{milestone.acceptanceCriteria}</p>
                  </div>
                </div>
              </div>))}
          </div>

          <div style={{ display: "flex", gap: "0.75rem" }}>
            <button onClick={() => setStep(1)} className="btn btn-ghost" style={{ flex: 1 }}>
              ← Regenerate
            </button>
            <button id="review-post-btn" onClick={() => setStep(3)} className="btn btn-primary" style={{ flex: 2 }}>
              Looks good → Review & Post
            </button>
          </div>
        </div>)}

      {/* ─── STEP 3: Review & Post ───────────────────────────────────────── */}
      {step === 3 && plan && (<div style={{ display: "flex", flexDirection: "column", gap: "1.25rem" }}>
          <div className="card">
            <h2 className="font-heading" style={{ fontSize: "1.1rem", fontWeight: 700, color: "white", marginBottom: "1.25rem" }}>Job Summary</h2>
            <div style={{ display: "grid", gap: "0.75rem" }}>
              <div style={{ display: "flex", justifyContent: "space-between", borderBottom: "1px solid hsl(220 20% 14%)", paddingBottom: "0.75rem" }}>
                <span style={{ color: "hsl(220 15% 55%)", fontSize: "0.875rem" }}>Title</span>
                <span style={{ color: "white", fontWeight: 600, fontSize: "0.875rem", maxWidth: "60%", textAlign: "right" }}>{title}</span>
              </div>
              <div style={{ display: "flex", justifyContent: "space-between", borderBottom: "1px solid hsl(220 20% 14%)", paddingBottom: "0.75rem" }}>
                <span style={{ color: "hsl(220 15% 55%)", fontSize: "0.875rem" }}>Total Budget</span>
                <span className="font-heading" style={{ color: "white", fontWeight: 800, fontSize: "1.1rem" }}>${budgetNum.toLocaleString()}</span>
              </div>
              <div style={{ display: "flex", justifyContent: "space-between", borderBottom: "1px solid hsl(220 20% 14%)", paddingBottom: "0.75rem" }}>
                <span style={{ color: "hsl(220 15% 55%)", fontSize: "0.875rem" }}>Milestones</span>
                <span style={{ color: "white", fontWeight: 600 }}>{plan.milestones.length} stages</span>
              </div>
              <div style={{ display: "flex", justifyContent: "space-between", borderBottom: "1px solid hsl(220 20% 14%)", paddingBottom: "0.75rem" }}>
                <span style={{ color: "hsl(220 15% 55%)", fontSize: "0.875rem" }}>Est. Duration</span>
                <span style={{ color: "white", fontWeight: 600 }}>{plan.estimatedDays} days</span>
              </div>
              <div style={{ display: "flex", justifyContent: "space-between" }}>
                <span style={{ color: "hsl(220 15% 55%)", fontSize: "0.875rem" }}>Skills</span>
                <div style={{ display: "flex", gap: "0.3rem", flexWrap: "wrap", justifyContent: "flex-end", maxWidth: "60%" }}>
                  {skills.map((s) => (<span key={s} style={{ fontSize: "0.7rem", background: "hsl(220 16% 14%)", color: "hsl(220 15% 65%)", padding: "0.1rem 0.4rem", borderRadius: 4 }}>{s}</span>))}
                </div>
              </div>
            </div>
          </div>

          {/* What happens next */}
          <div style={{ background: "hsl(217 91% 55% / 0.06)", border: "1px solid hsl(217 91% 55% / 0.15)", borderRadius: 12, padding: "1.25rem" }}>
            <div style={{ fontSize: "0.85rem", fontWeight: 700, color: "white", marginBottom: "1rem" }}>What happens after posting:</div>
            {[
                { icon: Cpu, color: "hsl(217 91% 65%)", text: "Gemini AI instantly matches your job to the top freelancers by skill fit and trust score" },
                { icon: Shield, color: "hsl(145 65% 50%)", text: "You review matches and hire — then fund the ILP escrow before work begins" },
                { icon: CheckCircle, color: "hsl(200 100% 60%)", text: "Freelancer submits each milestone — Gemini AI verifies against acceptance criteria" },
                { icon: Zap, color: "hsl(38 92% 55%)", text: "Approved milestones release payment instantly to the freelancer's ILP wallet" },
            ].map(({ icon: Icon, color, text }, i) => (<div key={i} style={{ display: "flex", alignItems: "flex-start", gap: "0.75rem", marginBottom: i < 3 ? "0.75rem" : 0 }}>
                <div style={{ width: 28, height: 28, borderRadius: 7, background: `${color}1a`, display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0, marginTop: "0.1rem" }}>
                  <Icon size={14} color={color}/>
                </div>
                <p style={{ fontSize: "0.82rem", color: "hsl(220 15% 65%)", lineHeight: 1.5 }}>{text}</p>
              </div>))}
          </div>

          <button id="final-post-btn" onClick={handlePost} disabled={posting} className="btn btn-primary" style={{ padding: "0.9rem 1.5rem", fontSize: "1rem", fontWeight: 700 }}>
            {posting ? (<><Loader2 size={18} style={{ animation: "spin 1s linear infinite" }}/> Posting...</>) : (<><Zap size={18}/> Post Job & Find Matches</>)}
          </button>

          <p style={{ fontSize: "0.75rem", color: "hsl(220 15% 40%)", textAlign: "center" }}>
            Your job goes live immediately. You'll be taken to AI match results.
          </p>
        </div>)}

      <style>{`@keyframes spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }`}</style>
    </div>);
}
